#!/bin/bash
#SBATCH --job-name=metaphlan
#SBATCH --array=0-26%10       ### 0-the number of files-1 % the amount you want to run at once
#SBATCH --cpus-per-task=8
#SBATCH --mem=24G
#SBATCH -p biosoc2
#SBATCH --time=72:00:00
#SBATCH --mail-type=END
#SBATCH --mail-user=alr34@kent.ac.uk
#SBATCH --output=/home/alr34/slurm/logs/%A_%a-metaphlan.out

set -euo pipefail

source ~/anaconda3/etc/profile.d/conda.sh
conda activate metaphlan_env
##change to match your project
DATA_DIR=~/blasto_meta/processed/PRJNA271618
OUT_DIR=~/blasto_meta/metaphlan_results

mkdir -p "$OUT_DIR"

mapfile -t SAMPLES < <(ls ${DATA_DIR}/*_R1.fastq.bz2 | sed 's/_R1.fastq.bz2//' | sort)

if [ "$SLURM_ARRAY_TASK_ID" -ge "${#SAMPLES[@]}" ]; then
    echo "Index out of range"
    exit 0
fi

SAMPLE=${SAMPLES[$SLURM_ARRAY_TASK_ID]}
BASE=$(basename "$SAMPLE")

echo "Running MetaPhlAn on $BASE"

metaphlan \
  ${SAMPLE}_R1.fastq.bz2,${SAMPLE}_R2.fastq.bz2 \
  --input_type fastq \
  --nproc 8 \
  --db_dir /home/alr34/metaphlan_db \
  -x mpa_vJan25_CHOCOPhlAnSGB_202503 \
  --mapout ${OUT_DIR}/${BASE}.map.bz2 \
  -o ${OUT_DIR}/${BASE}_profile.txt

conda deactivate
